Upgrade Zulu JDK to version 17
trinodb/docker-images pull request #104
Opened 2021-09-20 19:46 UTC by wendigo

2021-09-20 19:50 UTC, electrum approved these changes

2021-09-21 08:07 UTC, findepi requested changes
We should continue to test on the lowest JDK version supported.

2021-09-21 14:50 UTC, electrum commented
@findepi we decided to switch to start testing with JDK 17 so that we can move as quickly as possible. We need to tell people to start running on JDK 17 and get feedback about any potential problems. We don’t have the resources to test with both.

2021-09-21 14:51 UTC, merged

2021-09-21 21:35 UTC, losipiuk commented
> @findepi we decided to switch to start testing with JDK 17 so that we can move as quickly as possible. We need to tell people to start running on JDK 17 and get feedback about any potential problems. We don’t have the resources to test with both.

We discussed that today. It does not require more resources as we can just split product tests jobs so some Hadoop distros use the use of 11 and some 17. And have reasonable coverage for both until we decide that we can safely deprecate 11.

See https://github.com/trinodb/docker-images/pull/105