Rename presto to trino
trinodb/docker-images pull request #82
Opened 2021-01-05 11:03 UTC by Praveen2112

2021-01-05 12:52 UTC, findepi commented
We probably need to migrate from Travis to GHA asap (first?)

2021-01-05 12:55 UTC, findepi reviewed
LGTM, but the build is failing.

2021-01-05 12:55 UTC, findepi commented on trinodev/centos7-oj8/Dockerfile
> +# Install Java and trino-admin dependences
trino-admin does not exist yet. no change requested

2021-01-05 12:55 UTC, findepi commented on trinodev/hdp2.6-hive/Dockerfile
> +MAINTAINER Trino community <https://trinodb.io/community.html>
http 404, use slack.html instead

2021-01-05 16:35 UTC, electrum commented on trinodev/hdp2.6-hive/Dockerfile
> +MAINTAINER Trino community <https://trinodb.io/community.html>
We should remove this from all the images as it’s deprecated. There is a replacement label to indicate the maintainer, but I don’t see any value in having it. I’d rather just remove it.

2021-01-05 23:32 UTC, findepi commented on .travis.yml
> +  - IMAGE_TO_BUILD=trinodev/hdp3.1-hive-kerberized IMAGE_TO_TEST=hdp3.1-hive
`prestodev` was a Docker hub org name.
we're not going to use `trinodev` and the images on GHCR (github container registry) are prefixed with `testing/`, so i think the directory name should be `testing` too

cc @losipiuk

2021-01-06 10:27 UTC, Praveen2112 commented
trinodev is maintained as a environment variable and as a path in centos (not sure if we would need to have it as testing)

2021-01-06 19:29 UTC, ssheikin commented on Makefile
> +ORGDIR=testing
Seems this parameter can be inlined as `testing` is quite strange name for organisation.  
cc @findepi @losipiuk

2021-01-06 19:33 UTC, ssheikin commented on .travis.yml
> +  - IMAGE_TO_BUILD=testing/hdp2.6-hive-kerberized IMAGE_TO_TEST=hdp2.6-hive
is this file has to be deleted and this pr has to be based on https://github.com/trinodb/docker-images/pull/83 ?

2021-01-06 22:12 UTC, findepi commented on .travis.yml
> +  - IMAGE_TO_BUILD=trinodev/hdp3.1-hive-kerberized IMAGE_TO_TEST=hdp3.1-hive
BTW sphinx image is not for testing, so it should be `build/`

2021-01-06 22:17 UTC, findepi commented on Makefile
> +ORGDIR=testing
"prestodev" was an org in Docker Hub parlance.
in GHCR parlance the org is "trinodb", and the images are nested in arbitrarily deep directory structures... or there are no directories, just slashes in the names, how you prefer.
Thus, if ORG variable stays, it should have "trinodb" value.

2021-01-07 02:41 UTC, Praveen2112 commented on .travis.yml
> +  - IMAGE_TO_BUILD=testing/hdp2.6-hive-kerberized IMAGE_TO_TEST=hdp2.6-hive
It has to be on top of #83

2021-01-07 09:11 UTC, losipiuk commented on prestodev/cdh5.12-hive-kerberized/Dockerfile
> -MAINTAINER Presto community <https://prestosql.io/community.html>
Why not update to trino?

2021-01-07 09:12 UTC, losipiuk commented on prestodev/cdh5.12-hive-kerberized/Dockerfile
> -MAINTAINER Presto community <https://prestosql.io/community.html>
I personally do not care much - but maybe there was a reason to have it.

2021-01-07 09:24 UTC, Praveen2112 commented on prestodev/cdh5.12-hive-kerberized/Dockerfile
> -MAINTAINER Presto community <https://prestosql.io/community.html>
Reference : https://github.com/trinodb/docker-images/pull/82#discussion_r552048228

2021-01-07 12:46 UTC, ssheikin requested changes
It has to be on top of #83 https://github.com/trinodb/docker-images/pull/82/files#r553077636

2021-01-07 12:47 UTC, ssheikin requested changes
It has to be on top of #83

2021-01-14 09:07 UTC, ssheikin approved these changes

2021-01-14 09:11 UTC, kokosing commented
@Praveen2112 There are plenty of automation failures.

2021-01-14 14:13 UTC, kokosing commented on prestodev/hive3.1-hive/Dockerfile
>      mariadb-server \
There are some iop related files, please remove them.

2021-01-14 14:13 UTC, kokosing commented on Makefile
> +ORGDIR=testing
There are two directories: build and testing. Does makefile is able to build sphinx image?

2021-01-14 14:44 UTC, Praveen2112 commented on prestodev/hive3.1-hive/Dockerfile
>      mariadb-server \
I searched it .. It looks like most of the files are removed.

2021-01-14 14:46 UTC, Praveen2112 commented
> There are two directories: build and testing. Does makefile is able to build sphinx image?

I guess we don't build sphinx image. Ref : https://github.com/trinodb/docker-images/pull/77

2021-01-15 12:02 UTC, kokosing approved these changes

2021-01-15 13:04 UTC, losipiuk commented on prestodev/centos6-oj8-openldap-referrals/files/etc/openldap/setup/createReferrals.ldif
> -dn: ou=World,dc=presto,dc=testldap,dc=com
is this one gone?

2021-01-15 13:06 UTC, losipiuk reviewed
I think all name for all images should be `ghcr.io/trinodb/testing/...` not just `testing/...`. This is how we push them to ghcr and how we reference them from test code in trino.

Another option would be to keep `testing/...` here and only tag as `ghcr.io/trinodb/testing` before release and push, but I think it would be more confusing.

@findepi WDYT?

2021-01-15 13:08 UTC, Praveen2112 commented on prestodev/centos6-oj8-openldap-referrals/files/etc/openldap/setup/createReferrals.ldif
> -dn: ou=World,dc=presto,dc=testldap,dc=com
The file is replaed - testing/centos6-oj8-openldap-referrals/files/etc/openldap/setup/createReferrals.ldif

2021-01-15 13:41 UTC, findepi commented
> @findepi WDYT?

As long as it doesn't require us to have `ghcr.io/trinodb/testing` in the _file paths_, i like your proposal @losipiuk

2021-01-15 14:27 UTC, losipiuk commented
> > @findepi WDYT?
> 
> As long as it doesn't require us to have `ghcr.io/trinodb/testing` in the _file paths_, i like your proposal @losipiuk

We discussed it offline with @Praveen2112 and for now let's keep the image names during build shorter, and we will add extra tagging to release process which does the pushing. This will be addressed in followup PR.

2021-01-15 14:29 UTC, losipiuk approved these changes

2021-01-15 14:57 UTC, merged